name: Auto-update kernel

on:
  schedule:
    # daily, hour and minute chosen arbitrarily
    - cron: "32 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check latest kernel version from https://kernel.org
        id: check
        run: |
          # split lines to fail on exit != 0
          tag="$(go run ./cmd/check-update/main.go)"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Fetch latest kernel
        if: steps.check.outputs.tag != ''
        id: fetch
        run: |
          git config -f .gitmodules submodule.scripts.tag ${{steps.check.output.tag}}
          git submodule update --init --depth=1 linux-sources
          cd linux-sources
          git fetch --depth=1 origin ${{steps.check.outputs.tag}}
          git checkout ${{steps.check.outputs.tag}}

          # split lines to fail on exit != 0
          version="$(make kernelversion)"
          echo "version=$version" >> $GITHUB_OUTPUT
          cd ..
          git diff --no-ext-diff

      - name: Compile latest kernel
        if: steps.check.outputs.tag != ''
        run: go run cmd/compile/main.go

      - name: Show kernel config
        if: steps.check.outputs.tag != ''
        run: cat linux-sources/.config

      - name: Commit the new kernel
        if: steps.check.outputs.tag != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: kernel ${{steps.fetch.outputs.version}}
          tagging_message: v1.0.2-${{steps.fetch.outputs.version}}
